<a href="https://colab.research.google.com/github/majidsh97/Pipelines/blob/main/Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
from transformers import pipeline,AutoModel,AutoTokenizer
import torch
#https://github.com/stas00/ml-engineering?tab=readme-ov-file
name = "cardiffnlp/tweet-topic-21-multi"
classifier = pipeline(model=name)
#classifier(
#    "i wanna learn u eng",
    #candidate_labels=["urgent", "not urgent", "phone", "tablet", "computer"],
#)

model = AutoModel.from_pretrained(name,)
tokenizer = AutoTokenizer.from_pretrained(name)
class_mapping = model.config.id2label
model.pooler=torch.nn.Identity()
model.

et = tokenizer.encode("music",return_tensors='pt')
print(et.shape)
print(class_mapping)
print(et)
print(model)
print(tokenizer)
#model(et)

Some weights of RobertaModel were not initialized from the model checkpoint at cardiffnlp/tweet-topic-21-multi and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


torch.Size([1, 3])
{0: 'arts_&_culture', 1: 'business_&_entrepreneurs', 2: 'celebrity_&_pop_culture', 3: 'diaries_&_daily_life', 4: 'family', 5: 'fashion_&_style', 6: 'film_tv_&_video', 7: 'fitness_&_health', 8: 'food_&_dining', 9: 'gaming', 10: 'learning_&_educational', 11: 'music', 12: 'news_&_social_concern', 13: 'other_hobbies', 14: 'relationships', 15: 'science_&_technology', 16: 'sports', 17: 'travel_&_adventure', 18: 'youth_&_student_life'}
tensor([[    0, 28400,     2]])
RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): RobertaEncoder(
    (layer): ModuleList(
      (0-11): 12 x RobertaLayer(
        (attention): RobertaAttention(
          (self): RobertaSelfAttention(
            

In [18]:
from transformers import AutoModelForSequenceClassification, TFAutoModelForSequenceClassification
from transformers import AutoTokenizer
import numpy as np
import torch
from scipy.special import expit


MODEL = f"cardiffnlp/tweet-topic-21-multi"
tokenizer = AutoTokenizer.from_pretrained(MODEL)

# PT
model = AutoModelForSequenceClassification.from_pretrained(MODEL)
class_mapping = model.config.id2label

text = "It is great to see athletes promoting awareness for climate change."
tokens = tokenizer(text, return_tensors='pt')
output = model(**tokens)

print(model)
scores = output[0][0].detach().numpy()
scores = expit(scores)
predictions = (scores >= 0.5) * 1


# TF
#tf_model = TFAutoModelForSequenceClassification.from_pretrained(MODEL)
#class_mapping = tf_model.config.id2label
#text = "It is great to see athletes promoting awareness for climate change."
#tokens = tokenizer(text, return_tensors='tf')
#output = tf_model(**tokens)
#scores = output[0][0]
#scores = expit(scores)
#predictions = (scores >= 0.5) * 1

# Map to classes
for i in range(len(predictions)):
  if predictions[i]:
    print(class_mapping[i])


RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
             

In [44]:
o = model(et)[0][0].detach()

In [45]:
i = torch.where(torch.sigmoid( o )>0.5)[0].numpy()[0]
class_mapping[ i ]

'music'

In [50]:
for p in model.parameters():
    p.requires_grad = False

model(et)[0][0]


tensor([-3.1563, -5.6473, -1.3149, -2.9974, -4.8074, -5.1037, -3.4917, -4.5971,
        -5.0995, -5.8218, -5.8823,  3.4049, -2.6705, -4.7993, -4.5908, -5.0857,
        -5.2657, -5.5476, -5.8860])

In [54]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.5 MB/s eta 0:00:00


In [74]:
import datasets
from  torch.utils.data import DataLoader
data = datasets.load_dataset('tweet_eval','emotion')
encoded = data['train'].map( lambda x:tokenizer(x['text'],padding='max_length' , max_length = 128 , truncation=True))
encoded.set_format('pt',columns=['label', 'input_ids', 'attention_mask'])
dataloader = DataLoader(encoded , 1)


Map:   0%|          | 0/3257 [00:00<?, ? examples/s]

In [87]:
next(iter(dataloader))

for epoch in range(1):
  for batch in dataloader:
    label = batch['label']
    input_ids = batch['input_ids']
    attention_mask = batch['attention_mask']
    o = model.forward(input_ids=input_ids , attention_mask=attention_mask)
    print(o)
    break

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 4.1085e-01,  1.4477e-01,  4.4299e-01,  ..., -3.2366e+00,
           8.8056e-02,  9.5047e-01],
         [ 4.5796e-01, -1.4373e-01,  1.4571e-01,  ..., -4.2199e+00,
          -1.2918e-01,  9.2311e-01],
         [ 4.6748e-01, -5.6364e-02,  1.3866e-01,  ..., -4.1267e+00,
          -1.1875e-02,  9.8609e-01],
         ...,
         [ 2.7973e-01, -6.0964e-02,  1.9400e-01,  ..., -3.9597e+00,
          -1.6154e-01,  9.5168e-01],
         [ 2.7973e-01, -6.0964e-02,  1.9400e-01,  ..., -3.9597e+00,
          -1.6154e-01,  9.5168e-01],
         [ 2.7973e-01, -6.0964e-02,  1.9400e-01,  ..., -3.9597e+00,
          -1.6154e-01,  9.5168e-01]],

        [[ 3.8454e-01,  7.2449e-01,  9.1279e-01,  ..., -4.8497e-01,
           3.6834e-02,  2.8524e-02],
         [ 3.1482e-01,  5.7714e-01,  5.0656e-01,  ..., -9.9504e-01,
          -1.8375e-01,  2.3530e-01],
         [ 4.2957e-01,  6.2363e-01,  4.6783e-01,  ..., -9.2415e-01,
          -2.

In [88]:
o.last_hidden_state.shape

torch.Size([32, 128, 768])

In [89]:
o.pooler_output.shape

torch.Size([32, 128, 768])

In [72]:
attention_mask

[tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 0, 1, 1, 1, 1, 1]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 